config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  root to: 'products#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true  
end

app/models/product.rb
class Product < ApplicationRecord
  before_save(:titleize_product)
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(10)
    )}
    scope :ten_most_recent, -> { order(created_at: :desc).limit(3)}
    scope :search, -> (location_parameter) { where("country_of_origin like ?", "%#{location_parameter}%")}
    private
    def titleize_product

      self.name = self.name.titleize
    end
  end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  before_save(:titleize_author)

  private
  def titleize_author
    self.author = self.author.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  def home
    render :home
  end
  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
  def admin_access
    if !current_user.admin
      flash[:alert] = "You aren't authorized to visit that page. Not admin"
      redirect_to '/'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @most_reviews = Product.most_reviews.first
    render :index
  end

  def new
    @product= Product.new
    render :new
  end

  def create
    @product= Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product= Product.find(params[:id])
    render :edit
  end

  def show
    @product= Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product= Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Fields can't be blank!"
      render :new
    end
  end
  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end
  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end
  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
<%= f.label :name %> <br>
<%= f.text_field :name %> <br>
<%= f.label :cost %> <br>
<%= f.number_field :cost %> <br>
<%= f.label :country_of_origin %> <br>
<%= f.text_field :country_of_origin %> <br>
<%= f.submit %> 
<% end %>

app/views/layouts/application.html.erb
<%= stylesheet_link_tag "styles" %>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<!DOCTYPE html>
<html>
<head>
  <title>RailsMarioProducts</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div class="w3-top">
    <div class="w3-bar w3-white w3-wide w3-padding w3-card">
      <a href="#index" class="w3-bar-item w3-button"><b>MI</b> Mario Foods </a>
      <% if current_user %>
      <p class="w3-bar-item w3-button">
        <%= current_user.email %> | <%= link_to "Sign out", '/signout' %> </p>
        <% else %>
        <p class="w3-bar-item w3-button"> <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %> </p>
        <% end %>
      </div>
    </div>

    <header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
      <%= image_tag("fruit.jpeg", :alt => "food", :class => "image") %>
      <div class="w3-display-middle w3-margin-top w3-center">
        <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>MI</b></span> <span class="w3-hide-small w3-text-light-grey">Mario Foods</span></h1>
      </div>
    </header>
    <div id='flash'>
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div> <br>
    <div class="w3-content w3-padding" style="max-width:1564px">
      <%= yield %>
    </div>
  </body>
  </html>

app/views/products/__edit.html.erb
<% content_for(:title, "Edit Products") %>
<h1>Edit Product</h1>

<%= render "layouts/form" %>

app/views/products/__index.html.erb
<h1>Products</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>


<p><%= link_to "Create new product", new_product_path %></p>

app/views/products/__new.html.erb
<% if @product.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<% content_for(:title, "New Products") %>
<h1>New Product</h1>

<%= render "layouts/form" %>

app/views/products/__show.html.erb
<% content_for(:title, @product.name) %>
<h4><%= @product.name %></h4>
  <h5><%= @product.country %></h5>
<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.name, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/products/edit.html.erb
<h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Edit Product</h3>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<div class="w3-container w3-grey"> <h3>Products</h3>
  </div>
<% if @products.any? %>
<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet.</p>
<% end %> <br>
<% if @most_reviews  %>
<h5>The most reviewed products:</h5>
<h4><%= link_to @most_reviews.name, product_path(@most_reviews)%></h4>
<% end %>

<p><%= link_to "Create new product", new_product_path %></p>

app/views/products/new.html.erb
<h3>New Product</h3>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<% content_for(:title, @product.name) %>
<h4><div class="w3-container w3-grey"> product:<br>
</div> </h4>
<div class="w3-container"> <%= @product.name %>
</div>
<h5><div class="w3-container w3-grey">country<br>
</div>
<div class="w3-container"> <%= @product.country_of_origin %></h5>
</div>
<% if @product.reviews.any? %>
<h4>Here are the reviews for this product:</h4>

<% @product.reviews.each do |review| %>
<ul>
  <li>
    <%= link_to review.author, product_review_path(@product, review) %>
  </li>
</ul>
<% end %>
<% else %>
<p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
  :data => {:confirm => "Are you sure?",
  :method => "delete"} %></p>

  <p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h3>Edit review:</h3>

<%= form_for [@product, @review] do |f| %>
<%= f.label :author %> <br>
<%= f.text_field :author %> <br> <br>
<%= f.label :Did_you_like_our_product? %> <br>
<%= f.text_area :content_body %>
<%= f.label :rating %><br>
<%= f.number_field :rating, min: 1, max: 5, step: 1 %>
<p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h3>Add a new review:</h3>

<%= form_for [@product, @review] do |f| %>
<%= f.label :author %> <br>
<%= f.text_field :author %> <br> <br>
<%= f.label :Did_you_like_our_product? %> <br>
<%= f.text_area :content_body %>
<%= f.label :rating %><br>
<%= f.number_field :rating, min: 1, max: 5, step: 1 %>
<p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<h3>Review for <%= @product.name %>:</h3>
<div class="review">
<h4><div class="w3-container w3-grey"><%= @review.author %> <h4>
  </div>
<h6> <span id="rating"> <%= @review.rating %>/5</span></h6>
<h5><%= @review.content_body %></h5>
</div>
<% if current_user && current_user.admin %
<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
  :data => {:confirm => "Are you sure?",
  :method => "delete"} %></p>
 <% end %>
  <p><%= link_to "Return to product", product_path(@product) %></p>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
<%= f.label "Email" %> <br>
<%= f.text_field :email %> <br>
<%= f.label "Password" %> <br>
<%= f.password_field :password %> <br>
<%= f.label :password_confirmation %> <br>
<%= f.password_field :password_confirmation %> <br>
<%= f.label :admin %> <br>
<%= f.check_box :admin %> <br>
<%= f.submit "Sign Up" %> <br>
<% end %>